#pragma once

#include <Arduino.h>

// Generated by scripts/generate-setup-assets.py. Do not edit directly.
namespace EinqSetupAssets {
constexpr char kIndexMime[] = "text/html; charset=utf-8";
constexpr char kIndex[] PROGMEM = R"EINQ_HTML(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#f4f1e8">
  <title>Mynah X3/X4 Setup</title>
  <link rel="manifest" href="/manifest.webmanifest">
  <link rel="stylesheet" href="/app.css?v=3">
</head>
<body>
  <header class="topbar">
    <div class="brand">
      <span class="brand-mark" aria-hidden="true">M</span>
      <span><strong>Mynah eInq</strong><small id="device-status">Connecting</small></span>
    </div>
    <button class="icon-button" id="refresh-button" type="button" title="Reload device settings" aria-label="Reload device settings">
      <span aria-hidden="true">↻</span>
    </button>
  </header>

  <main>
    <nav class="steps" aria-label="Setup sections">
      <button class="step active" type="button" data-panel="device"><span>1</span>Device</button>
      <button class="step" type="button" data-panel="profile"><span>2</span>Profile</button>
      <button class="step" type="button" data-panel="services"><span>3</span>Services</button>
      <button class="step" type="button" data-panel="rooms"><span>4</span>Rooms</button>
    </nav>

    <form id="config-form">
      <section class="panel active" id="panel-device" data-panel="device">
        <div class="section-heading">
          <p class="eyebrow">Hardware</p>
          <h1>Make this device at home</h1>
          <p>Name it for the person or place it belongs to. Mynah eInq runs on CrossPoint across both models.</p>
        </div>
        <div class="field-grid">
          <label class="field">
            <span>Device name</span>
            <input id="device-name" name="deviceName" maxlength="32" autocomplete="off" required>
          </label>
          <fieldset class="field">
            <legend>Hardware</legend>
            <div class="segmented">
              <label><input type="radio" name="board" value="x3"><span>Mynah X3</span></label>
              <label><input type="radio" name="board" value="x4"><span>Mynah X4</span></label>
            </div>
          </fieldset>
        </div>
        <div class="network-band">
          <span><strong>WiFi network</strong><small id="network-name">Not configured</small></span>
          <button class="secondary" id="change-wifi" type="button">Change</button>
        </div>
        <div class="wifi-fields" id="wifi-fields" hidden>
          <label class="field">
            <span>Primary network</span>
            <input id="wifi-primary-ssid" autocomplete="ssid" maxlength="32">
          </label>
          <label class="field">
            <span>Primary password</span>
            <input id="wifi-primary-password" type="password" autocomplete="current-password" maxlength="64">
          </label>
          <label class="field">
            <span>Backup network</span>
            <input id="wifi-backup-ssid" maxlength="32">
          </label>
          <label class="field">
            <span>Backup password</span>
            <input id="wifi-backup-password" type="password" autocomplete="current-password" maxlength="64">
          </label>
          <button class="secondary" id="save-wifi" type="button">Save WiFi</button>
        </div>
      </section>

      <section class="panel" id="panel-profile" data-panel="profile">
        <div class="section-heading">
          <p class="eyebrow">Household policy</p>
          <h1>Choose who this is for</h1>
          <p>The profile controls what appears and which household actions are available.</p>
        </div>
        <fieldset class="choice-list">
          <legend class="sr-only">Profile</legend>
          <label class="choice">
            <input type="radio" name="profile" value="parent">
            <span><strong>Parent</strong><small>Personal calendar, household controls, and full Castalia catalog</small></span>
          </label>
          <label class="choice">
            <input type="radio" name="profile" value="kid">
            <span><strong>Kid</strong><small>Family calendar, approved scenes, and age-aware content</small></span>
          </label>
        </fieldset>
        <label class="field age-field" id="age-field">
          <span>Content age band</span>
          <select id="age-band" name="ageBand">
            <option value="child">Child</option>
            <option value="tween">Tween</option>
            <option value="teen">Teen</option>
          </select>
        </label>
        <div class="toggle-list">
          <label class="toggle"><span><strong>Calendar</strong><small>Show today and the next event</small></span><input type="checkbox" name="calendarEnabled"></label>
          <label class="toggle"><span><strong>Astrology</strong><small>Daily Astrolabe reading</small></span><input type="checkbox" name="astrologyEnabled"></label>
          <label class="toggle"><span><strong>Fortunes</strong><small>Daily draw and reflection</small></span><input type="checkbox" name="fortuneEnabled"></label>
          <label class="toggle"><span><strong>eINQ cards</strong><small>Scheduled Castalia inquiry cards</small></span><input type="checkbox" name="cardsEnabled"></label>
        </div>
        <label class="field">
          <span>Household calendar ID</span>
          <input id="calendar-id" name="calendarId" maxlength="192" autocomplete="off"
                 placeholder="Calendar address configured by a parent">
        </label>
      </section>

      <section class="panel" id="panel-services" data-panel="services">
        <div class="section-heading">
          <p class="eyebrow">Connections</p>
          <h1>Bring in useful things</h1>
          <p>Accounts connect through Castalia. Vendor credentials are never stored on the e-paper device.</p>
        </div>
        <div class="service-list">
          <article class="service">
            <span class="service-mark castalia" aria-hidden="true">C</span>
            <span><strong>Castalia household</strong><small id="castalia-state">Not paired</small></span>
            <button class="secondary" type="button" data-connect="castalia">Pair</button>
          </article>
          <article class="service">
            <span class="service-mark calendar" aria-hidden="true">31</span>
            <span><strong>Calendar</strong><small>Connected by a parent</small></span>
            <button class="secondary" type="button" data-connect="calendar">Connect</button>
          </article>
          <article class="service">
            <span class="service-mark spotify" aria-hidden="true">S</span>
            <span><strong>Spotify</strong><small>Remote control for a Connect player</small></span>
            <button class="secondary" type="button" data-connect="spotify">Connect</button>
          </article>
          <article class="service">
            <span class="service-mark lights" aria-hidden="true">L</span>
            <span><strong>Home Assistant</strong><small>Local bridge for allow-listed Tuya lights</small></span>
            <button class="secondary" type="button" data-connect="home-assistant">Connect</button>
          </article>
        </div>
        <label class="field">
          <span>Castalia gateway</span>
          <input id="gateway-url" name="gatewayUrl" type="url" inputmode="url" placeholder="https://mynah.castalia.institute">
        </label>
      </section>

      <section class="panel" id="panel-rooms" data-panel="rooms">
        <div class="section-heading">
          <p class="eyebrow">Room awareness</p>
          <h1>Teach eInq where it is</h1>
          <p>Assign one BLE beacon to each room. Signal smoothing keeps controls from jumping between nearby rooms.</p>
        </div>
        <div id="room-list" class="room-list"></div>
        <button class="secondary add-room" id="add-room" type="button"><span aria-hidden="true">+</span>Add room</button>
        <div class="confidence">
          <label for="room-confidence"><span><strong>Switch confidence</strong><small>Higher values reduce accidental room changes</small></span></label>
          <output id="room-confidence-value">5 dB</output>
          <input id="room-confidence" name="roomMinimumLead" type="range" min="2" max="15" step="1">
        </div>
      </section>

      <footer class="actions">
        <p id="save-state" role="status">Settings load from your eInq.</p>
        <button class="primary" id="save-config" type="submit">Save settings</button>
      </footer>
    </form>
  </main>

  <template id="room-template">
    <article class="room-row">
      <label class="field"><span>Room name</span><input data-room-name maxlength="31" placeholder="Kitchen"></label>
      <label class="field"><span>Beacon ID</span><input data-beacon-id maxlength="63" placeholder="Address, name, or iBeacon ID"></label>
      <button class="icon-button remove-room" type="button" title="Remove room" aria-label="Remove room"><span aria-hidden="true">×</span></button>
    </article>
  </template>
  <script src="/app.js?v=3" defer></script>
</body>
</html>
)EINQ_HTML";

constexpr char kCssMime[] = "text/css; charset=utf-8";
constexpr char kCss[] PROGMEM = R"EINQ_CSS(:root {
  color-scheme: light;
  --paper: #f4f1e8;
  --surface: #fffefa;
  --ink: #18201d;
  --muted: #66706a;
  --line: #d6d7cf;
  --green: #20634f;
  --green-dark: #164638;
  --yellow: #f0c95b;
  --blue: #3c6478;
  --danger: #a43c32;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size: 16px;
}

* { box-sizing: border-box; }
[hidden] { display: none !important; }
body { margin: 0; background: var(--paper); color: var(--ink); min-width: 320px; }
button, input, select { font: inherit; }
button { cursor: pointer; }
button:disabled { cursor: not-allowed; opacity: .48; }

.topbar {
  min-height: 72px;
  padding: 12px clamp(18px, 4vw, 48px);
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid var(--line);
  background: rgba(255, 254, 250, .92);
}

.brand, .brand > span:last-child, .network-band > span, .service > span:nth-child(2), .toggle > span {
  display: flex;
  align-items: flex-start;
}
.brand { gap: 12px; align-items: center; }
.brand > span:last-child, .network-band > span, .service > span:nth-child(2), .toggle > span { flex-direction: column; }
.brand strong { font-size: 1rem; }
small { color: var(--muted); font-size: .78rem; line-height: 1.4; }

.brand-mark {
  display: grid;
  place-items: center;
  width: 38px;
  height: 38px;
  border-radius: 50%;
  background: var(--ink);
  color: var(--paper);
  font-family: Georgia, serif;
  font-size: 1.25rem;
}

.icon-button {
  width: 40px;
  height: 40px;
  display: grid;
  place-items: center;
  border: 1px solid var(--line);
  background: var(--surface);
  color: var(--ink);
  border-radius: 6px;
  font-size: 1.4rem;
}
.icon-button:hover { border-color: var(--green); color: var(--green); }

main { width: min(900px, 100%); margin: 0 auto; padding: 28px clamp(16px, 4vw, 42px) 48px; }
.steps { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin-bottom: 34px; }
.step {
  min-height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  border: 0;
  border-bottom: 2px solid var(--line);
  background: transparent;
  color: var(--muted);
  font-size: .84rem;
  font-weight: 700;
}
.step span {
  display: grid;
  place-items: center;
  width: 22px;
  height: 22px;
  border: 1px solid currentColor;
  border-radius: 50%;
  font-size: .72rem;
}
.step.active { color: var(--green-dark); border-color: var(--green); }
.step.active span { background: var(--green); color: white; border-color: var(--green); }

.panel { display: none; }
.panel.active { display: block; }
.section-heading { max-width: 640px; margin-bottom: 28px; }
.eyebrow { color: var(--green); font-size: .72rem; font-weight: 800; text-transform: uppercase; margin: 0 0 7px; }
h1 { font-family: Georgia, serif; font-size: clamp(1.8rem, 5vw, 2.45rem); font-weight: 500; margin: 0 0 8px; }
.section-heading > p:last-child { color: var(--muted); line-height: 1.55; margin: 0; }

.field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
.field { display: flex; flex-direction: column; gap: 7px; border: 0; padding: 0; margin: 0 0 18px; min-width: 0; }
.field > span, .field legend { font-size: .78rem; font-weight: 750; color: #39413d; }
input:not([type="radio"]):not([type="checkbox"]):not([type="range"]), select {
  width: 100%;
  min-height: 46px;
  border: 1px solid #bfc3bc;
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  padding: 10px 12px;
}
input:focus, select:focus, button:focus-visible { outline: 3px solid rgba(32, 99, 79, .2); outline-offset: 1px; }

.segmented { display: grid; grid-template-columns: 1fr 1fr; }
.segmented label { position: relative; }
.segmented input { position: absolute; opacity: 0; }
.segmented span {
  min-height: 46px;
  display: grid;
  place-items: center;
  border: 1px solid #bfc3bc;
  background: var(--surface);
  font-weight: 700;
}
.segmented label:first-child span { border-radius: 6px 0 0 6px; }
.segmented label:last-child span { border-radius: 0 6px 6px 0; border-left: 0; }
.segmented input:checked + span { color: white; background: var(--green); border-color: var(--green); }

.network-band, .service {
  display: flex;
  align-items: center;
  gap: 14px;
  border-top: 1px solid var(--line);
  padding: 16px 0;
}
.network-band { justify-content: space-between; margin-top: 12px; }
.wifi-fields { padding: 18px; border-left: 3px solid var(--yellow); background: var(--surface); }
.primary, .secondary {
  min-height: 40px;
  border-radius: 6px;
  padding: 9px 16px;
  font-weight: 750;
}
.primary { border: 1px solid var(--green); background: var(--green); color: white; }
.primary:hover { background: var(--green-dark); }
.secondary { border: 1px solid #aeb4ad; background: var(--surface); color: var(--ink); }
.secondary:hover { border-color: var(--green); color: var(--green); }

.choice-list { border: 0; padding: 0; margin: 0 0 24px; display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.choice { position: relative; }
.choice input { position: absolute; opacity: 0; }
.choice > span {
  min-height: 104px;
  display: flex;
  flex-direction: column;
  gap: 5px;
  padding: 18px;
  border: 1px solid var(--line);
  border-radius: 6px;
  background: var(--surface);
}
.choice input:checked + span { border: 2px solid var(--green); padding: 17px; }
.age-field { max-width: 260px; }
.toggle-list { border-top: 1px solid var(--line); }
.toggle { display: flex; justify-content: space-between; align-items: center; gap: 16px; min-height: 68px; border-bottom: 1px solid var(--line); }
.toggle input {
  appearance: none;
  width: 44px;
  height: 24px;
  flex: 0 0 auto;
  padding: 3px;
  border-radius: 20px;
  background: #aeb4ad;
}
.toggle input::after { content: ""; display: block; width: 18px; height: 18px; border-radius: 50%; background: white; transition: transform .15s ease; }
.toggle input:checked { background: var(--green); }
.toggle input:checked::after { transform: translateX(20px); }

.service-list { border-bottom: 1px solid var(--line); margin-bottom: 24px; }
.service > span:nth-child(2) { flex: 1; min-width: 0; }
.service-mark {
  width: 38px;
  height: 38px;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  border-radius: 50%;
  font-weight: 800;
}
.service-mark.castalia { background: var(--ink); color: var(--paper); font-family: Georgia, serif; }
.service-mark.calendar { background: #d95446; color: white; font-size: .75rem; }
.service-mark.spotify { background: #1ed760; color: #102218; }
.service-mark.lights { background: var(--yellow); color: #3b3216; }

.room-list { display: flex; flex-direction: column; gap: 10px; }
.room-row { display: grid; grid-template-columns: .8fr 1.2fr 40px; gap: 12px; align-items: end; padding: 14px; border: 1px solid var(--line); background: var(--surface); border-radius: 6px; }
.room-row .field { margin: 0; }
.remove-room { color: var(--danger); }
.add-room { margin: 14px 0 28px; }
.add-room span { font-size: 1.2rem; margin-right: 7px; }
.confidence { display: grid; grid-template-columns: 1fr auto; gap: 12px; border-top: 1px solid var(--line); padding-top: 22px; }
.confidence label span { display: flex; flex-direction: column; }
.confidence output { font-weight: 800; color: var(--green); }
.confidence input { grid-column: 1 / -1; width: 100%; accent-color: var(--green); }

.actions { display: flex; justify-content: space-between; align-items: center; gap: 20px; margin-top: 34px; padding-top: 20px; border-top: 1px solid var(--line); }
.actions p { color: var(--muted); font-size: .82rem; margin: 0; }
.actions p.error { color: var(--danger); }
.sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0; }

@media (max-width: 620px) {
  .topbar { min-height: 62px; }
  main { padding-top: 18px; }
  .steps { margin-bottom: 26px; }
  .step { font-size: 0; gap: 0; }
  .step span { font-size: .72rem; }
  .field-grid, .choice-list { grid-template-columns: 1fr; }
  .room-row { grid-template-columns: 1fr 40px; }
  .room-row .field:nth-child(2) { grid-column: 1 / -1; grid-row: 2; }
  .room-row .remove-room { grid-column: 2; grid-row: 1; }
  .service { align-items: flex-start; }
  .service .secondary { padding: 8px 10px; }
  .actions { align-items: stretch; flex-direction: column; }
  .actions .primary { width: 100%; }
}
)EINQ_CSS";

constexpr char kJsMime[] = "application/javascript; charset=utf-8";
constexpr char kJs[] PROGMEM = R"EINQ_JS(const defaultConfig = {
  schemaVersion: 1,
  deviceName: "Mynah eInq",
  board: "x3",
  profile: "parent",
  ageBand: "child",
  gatewayUrl: "https://mynah.castalia.institute",
  calendarId: "ca7a560e76044c59bbb72a70b98a21a774b99c2f5195eb7357ecd1a1cdf74344@group.calendar.google.com",
  features: { calendar: true, astrology: true, fortune: true, cards: true },
  rooms: [],
  roomMinimumLead: 5
};

const form = document.querySelector("#config-form");
const saveState = document.querySelector("#save-state");
const roomList = document.querySelector("#room-list");
const roomTemplate = document.querySelector("#room-template");
const confidence = document.querySelector("#room-confidence");
let config = structuredClone(defaultConfig);
let canWrite = true;

function setStatus(message, isError = false) {
  saveState.textContent = message;
  saveState.classList.toggle("error", isError);
}

function showPanel(name) {
  document.querySelectorAll(".panel").forEach((panel) => panel.classList.toggle("active", panel.dataset.panel === name));
  document.querySelectorAll(".step").forEach((step) => step.classList.toggle("active", step.dataset.panel === name));
}

function updateProfileUi() {
  const profile = form.elements.profile.value;
  document.querySelector("#age-field").hidden = profile !== "kid";
}

function addRoom(room = { name: "", beaconId: "", calibrationOffset: 0 }) {
  const fragment = roomTemplate.content.cloneNode(true);
  const row = fragment.querySelector(".room-row");
  row.querySelector("[data-room-name]").value = room.name || "";
  row.querySelector("[data-beacon-id]").value = room.beaconId || "";
  row.querySelector(".remove-room").addEventListener("click", () => row.remove());
  roomList.append(row);
}

function render(next) {
  config = { ...defaultConfig, ...next, features: { ...defaultConfig.features, ...(next.features || {}) } };
  form.elements.deviceName.value = config.deviceName;
  form.elements.board.value = config.board;
  form.elements.profile.value = config.profile;
  form.elements.ageBand.value = config.ageBand;
  form.elements.gatewayUrl.value = config.gatewayUrl;
  form.elements.calendarId.value = config.calendarId || "";
  form.elements.calendarEnabled.checked = config.features.calendar;
  form.elements.astrologyEnabled.checked = config.features.astrology;
  form.elements.fortuneEnabled.checked = config.features.fortune;
  form.elements.cardsEnabled.checked = config.features.cards;
  confidence.value = config.roomMinimumLead;
  document.querySelector("#room-confidence-value").value = `${confidence.value} dB`;
  roomList.replaceChildren();
  (config.rooms || []).forEach(addRoom);
  if (!config.rooms?.length) addRoom();
  updateProfileUi();
}

function collect() {
  const rooms = [...roomList.querySelectorAll(".room-row")].map((row) => ({
    name: row.querySelector("[data-room-name]").value.trim(),
    beaconId: row.querySelector("[data-beacon-id]").value.trim(),
    calibrationOffset: 0
  })).filter((room) => room.name && room.beaconId);
  return {
    schemaVersion: 1,
    deviceName: form.elements.deviceName.value.trim(),
    board: form.elements.board.value,
    profile: form.elements.profile.value,
    ageBand: form.elements.ageBand.value,
    gatewayUrl: form.elements.gatewayUrl.value.trim(),
    calendarId: form.elements.calendarId.value.trim(),
    features: {
      calendar: form.elements.calendarEnabled.checked,
      astrology: form.elements.astrologyEnabled.checked,
      fortune: form.elements.fortuneEnabled.checked,
      cards: form.elements.cardsEnabled.checked
    },
    rooms,
    roomMinimumLead: Number(confidence.value)
  };
}

async function loadConfig() {
  setStatus("Loading settings…");
  try {
    const response = await fetch("/api/v1/config", { headers: { Accept: "application/json" } });
    if (!response.ok) throw new Error(`Device returned ${response.status}`);
    render(await response.json());
    document.querySelector("#device-status").textContent = "Connected";
    setStatus("Settings loaded from your eInq.");
  } catch (error) {
    render(defaultConfig);
    document.querySelector("#device-status").textContent = "Preview";
    setStatus("Device API unavailable; showing a local preview.", true);
  }
}

async function loadDeviceStatus() {
  try {
    const response = await fetch("/api/v1/device", { headers: { Accept: "application/json" } });
    if (!response.ok) return;
    const status = await response.json();
    canWrite = status.canWrite !== false;
    document.querySelector("#network-name").textContent = status.network || "Not configured";
    document.querySelector("#save-config").disabled = !canWrite;
    document.querySelector("#change-wifi").disabled = !canWrite;
    if (!canWrite) {
      setStatus("Read-only on the home network. Long-press the Mynah setup button to make changes.");
    }
  } catch {
    // Static preview and older firmware do not expose device status.
  }
}

form.addEventListener("submit", async (event) => {
  event.preventDefault();
  if (!canWrite) {
    setStatus("Open physical setup mode on the Mynah before saving.", true);
    return;
  }
  const next = collect();
  setStatus("Saving settings…");
  try {
    const response = await fetch("/api/v1/config", {
      method: "PUT",
      headers: { "Content-Type": "application/json", Accept: "application/json" },
      body: JSON.stringify(next)
    });
    if (!response.ok) throw new Error(await response.text());
    render(await response.json());
    setStatus("Settings saved.");
  } catch (error) {
    setStatus(`Could not save: ${error.message}`, true);
  }
});

document.querySelectorAll(".step").forEach((step) => step.addEventListener("click", () => showPanel(step.dataset.panel)));
document.querySelectorAll("[name=profile]").forEach((input) => input.addEventListener("change", updateProfileUi));
document.querySelector("#add-room").addEventListener("click", () => addRoom());
document.querySelector("#refresh-button").addEventListener("click", loadConfig);
confidence.addEventListener("input", () => { document.querySelector("#room-confidence-value").value = `${confidence.value} dB`; });

document.querySelector("#change-wifi").addEventListener("click", () => {
  const fields = document.querySelector("#wifi-fields");
  fields.hidden = !fields.hidden;
});
document.querySelector("#save-wifi").addEventListener("click", async () => {
  if (!canWrite) {
    setStatus("Open physical setup mode on the Mynah before changing WiFi.", true);
    return;
  }
  const body = new URLSearchParams({
    primarySsid: document.querySelector("#wifi-primary-ssid").value,
    primaryPassword: document.querySelector("#wifi-primary-password").value,
    backupSsid: document.querySelector("#wifi-backup-ssid").value,
    backupPassword: document.querySelector("#wifi-backup-password").value
  });
  const response = await fetch("/wifi", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body });
  if (response.ok) {
    document.querySelector("#network-name").textContent = document.querySelector("#wifi-primary-ssid").value;
    setStatus("WiFi saved. Reconnect to the home network.");
  } else {
    setStatus("WiFi could not be saved.", true);
  }
});

document.querySelectorAll("[data-connect]").forEach((button) => button.addEventListener("click", () => {
  setStatus(`${button.dataset.connect} connection opens after this device is paired with Castalia.`);
}));

if ("serviceWorker" in navigator && window.isSecureContext) {
  navigator.serviceWorker.register("/sw.js").catch(() => {});
}

async function initialize() {
  await loadConfig();
  await loadDeviceStatus();
}

initialize();
)EINQ_JS";

constexpr char kManifestMime[] = "application/manifest+json";
constexpr char kManifest[] PROGMEM = R"EINQ_MANIFEST({
  "name": "Mynah X3/X4 Setup",
  "short_name": "Mynah Setup",
  "description": "Configure a Castalia Mynah eInq device.",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#f4f1e8",
  "theme_color": "#f4f1e8",
  "icons": []
}
)EINQ_MANIFEST";

constexpr char kServiceWorkerMime[] = "application/javascript; charset=utf-8";
constexpr char kServiceWorker[] PROGMEM = R"EINQ_SW(const cacheName = "einq-setup-v3";
const shell = ["/", "/app.css?v=3", "/app.js?v=3", "/manifest.webmanifest"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(shell)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== cacheName).map((key) => caches.delete(key)))));
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET" || new URL(event.request.url).pathname.startsWith("/api/")) return;
  event.respondWith(fetch(event.request).then((response) => {
    const copy = response.clone();
    caches.open(cacheName).then((cache) => cache.put(event.request, copy));
    return response;
  }).catch(() => caches.match(event.request)));
});
)EINQ_SW";

}  // namespace EinqSetupAssets
