#!/usr/bin/env python3
"""Generate the PROGMEM setup assets header from apps/setup-pwa."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "apps" / "setup-pwa"
OUTPUT = ROOT / "firmware" / "einq-wifi" / "EinqSetupAssets.h"
ASSETS = (
    ("Index", "index.html", "text/html; charset=utf-8", "HTML"),
    ("Css", "app.css", "text/css; charset=utf-8", "CSS"),
    ("Js", "app.js", "application/javascript; charset=utf-8", "JS"),
    ("Manifest", "manifest.webmanifest", "application/manifest+json", "MANIFEST"),
    ("ServiceWorker", "sw.js", "application/javascript; charset=utf-8", "SW"),
)


def raw_literal(text: str, token: str) -> str:
    delimiter = f"EINQ_{token}"
    if f"){delimiter}\"" in text:
        raise ValueError(f"raw string delimiter collision in {suffix}")
    return f'R"{delimiter}({text}){delimiter}"'


parts = [
    "#pragma once",
    "",
    "#include <Arduino.h>",
    "",
    "// Generated by scripts/generate-setup-assets.py. Do not edit directly.",
    "namespace EinqSetupAssets {",
]
for symbol, filename, mime, token in ASSETS:
    content = (SOURCE / filename).read_text(encoding="utf-8")
    parts.extend(
        [
            f'constexpr char k{symbol}Mime[] = "{mime}";',
            f"constexpr char k{symbol}[] PROGMEM = {raw_literal(content, token)};",
            "",
        ]
    )
parts.extend(["}  // namespace EinqSetupAssets", ""])
OUTPUT.write_text("\n".join(parts), encoding="utf-8")
print(f"generated {OUTPUT.relative_to(ROOT)}")
